### ISSUE TITLE
Doesn't work on Android 6.0

### ISSUE THREAD

**Issue by NGame1** [wilsonvargas/ButtonCirclePlugin#1]
Hi I test your Nuget and also the link below :
https://forums.xamarin.com/discussion/94559/circle-button-in-xamarin-forms-super-easy-way
your Nuget result this on emulator :
![image](https://user-images.githubusercontent.com/19765248/29290973-40c75784-8157-11e7-9d0d-ec7f89024632.png)
and the link I mention make a regular button with no change .
is it your Nuget bug or Android 6 change or Emulator bug .
I get confused !

**Comment by wilsonvargas** [comment]
Hi @NGame1 this is a problem only in Android 6.0 but it is solved by adding the BorderRadius property and assigning it the same value as the height of the button. something like this:

```xml
<local:CircleButton Icon="ic_directions_bike" 
                            FontSize="30" TextColor="Black"
                            HeightRequest="70" WidthRequest="70" 
                            BorderRadius="70" BackgroundColor="#DCDCDC"/>
        <!--This button is not exactly circular-->
        <local:CircleButton FontSize="30" TextColor="Black" 
                            HeightRequest="70" WidthRequest="200" 
                            BorderRadius="20" BackgroundColor="#DCDCDC"/>
```

![photo](https://user-images.githubusercontent.com/22247447/29342513-cdd53418-81f0-11e7-843a-37e7ae499248.png)

This property allows you to create buttons that are not exactly circular, as seen in the image.

I hope this helps you, your answer will help me close this issue 😄

**Comment by NGame1** [comment]
Thanks , It solved .

**Comment by pirou** [comment]
Hi, i had round buttons on Android with samsung galaxy S7 with android 8 but square ones with Huawei P20 on Android 9.
THe border radius trick seems to solve the problem !
