### ISSUE TITLE
Multi Line Labels in Buttons

### ISSUE THREAD

**Issue by AndyT4ME** [wilsonvargas/ButtonCirclePlugin#11]
I noticed a difference when deploying to iphone and android..

When I need two lines of text within the button normally in XAML we can use this

      <local:CircleButton x:Name="Order" FontSize="Large" TextColor="Black" 
                            Text="Orders&#x0a;&#x0a;10"
                            HeightRequest="100" BorderRadius="100" WidthRequest="100" Margin="-50,-50,-50,-50"
                            BorderColor="Black" BorderThickness="5" BackgroundColor="Orange"
                            Clicked="onCircleButton_Clicked" Grid.Row="2" Grid.Column="1" />

This works great on Android and I get the text "Orders" with the number Below it...

On the iphone I just get the text "Orders" and it appears the additional lines of text where not present.

**Comment by wilsonvargas** [comment]
This is mainly a problem with iOS because Android will wrap the text by default. I'm work in this I'll add this feature to next version.

**Comment by wilsonvargas** [comment]
Check latest [version (1.2.52)](https://www.nuget.org/packages/Plugins.Forms.ButtonCircle/1.2.52). I tested this version on an IPhone with iOS 11, Samsung Galaxy S8 with Android 7.1 and in my computer with Windows 10, it's work fine.

Please tell me if you have a issue again.

**Comment by AndyT4ME** [comment]
Thats Excellent I will test today

**Comment by AndyT4ME** [comment]
Works perfect !!!

Thank you for the support.

**Comment by ryebri** [comment]
This functionality is not currently working on GTK#.  When I insert a new line character it does not wrap the next text down into a second line.  Instead, the new line character is displayed
