### ISSUE TITLE
Loses overlay on Android

### ISSUE THREAD

**Issue by daveclarke** [wilsonvargas/ButtonCirclePlugin#12]
ButtonCircle looks good on iOS but on Android it can lose the overlay  and just look like an icon. When I first load my app it tries to login the user. When it does that it pops up a modal dialog with "Signing in...". I can see the circle underneath the signing in message but when the user is signed in and the modal is dismissed, the circle is gone. It still functions correctly but looks odd.

**Comment by wilsonvargas** [comment]
do you have any screenshot?

**Comment by daveclarke** [comment]
Sorry - I've just replaced ButtonCircle with an Image + TapGestureRecognizer - my ux testing feedback indicated I was using an icon that wasn't appropriate and the new one looks better without the circle.
