### ISSUE TITLE
Defect with binding the Icon property (and a solution provided below)

### ISSUE THREAD

**Issue by saadyacu** [wilsonvargas/ButtonCirclePlugin#14]
Here is the solution to the defect

I have noticed that the Icon property in the file [ButtonCirclePlugin / src / ButtonCircle / ButtonCircle.FormsPlugin.Abstractions / CircleButton.cs ] has a typo as below

48         /// <summary> 
49         /// Property definition for the <see cref="Icon"/> Property 
50         /// </summary> 
51         public static readonly BindableProperty IconProperty = 
52         BindableProperty.Create(propertyName: nameof(**_BorderColor_**), 
53               returnType: typeof(Icons), 
54               declaringType: typeof(CircleButton), 
55               defaultValue: Icons.ic_default); 

where the BorderColor is probably a cut-paste error and it should read Icon instead

Would love to see this fix make it to a new build

BTW: Thank you for a great control...

Saad (saad@yacu.net)

**Comment by wilsonvargas** [comment]
Thank you very much! I hadn't noticed this issue. I have added this change to new build. Pls check current version ([1.2.53](https://www.nuget.org/packages/Plugins.Forms.ButtonCircle))
