### ISSUE TITLE
Background Color Transparent is Black on Android?

### ISSUE THREAD

**Issue by CarlosMobileAppDeveloper** [wilsonvargas/ButtonCirclePlugin#19]
While trying to set the background color to transparent, it appears to be black instead? 
Tried using hex as well as the key-word.
Happens on Android. (Samsung S8 - Android 7.0)

**Comment by wilsonvargas** [comment]
@CarlosMobileAppDeveloper maybe you might solve this issue updating your Xamarin.Forms version to 2.5.1.444934 check this [project](https://github.com/wilsonvargas/XamarinChatBot/tree/master/src/ChatBot.Clients), I use my plugin and work fine.

**Comment by fbede4** [comment]
Hi, I user Xamarin.Forms 4.1.0.581479, and I now face a similar issue (grey background instead of transparent. It worked fine before. (Android 8.1)
