### ISSUE TITLE
Will there be netstandard support?

### ISSUE THREAD

**Issue by hlubovac** [wilsonvargas/ButtonCirclePlugin#20]

**Comment by wilsonvargas** [comment]
Yes there will be support for .Net Standard in next days.

**Comment by wilsonvargas** [comment]
can you test this version [2.0.1-beta](https://www.nuget.org/packages/Plugins.Forms.ButtonCircle/2.0.1-beta) pls? I going to close this issue 🥇

**Comment by hlubovac** [comment]
I was previously stuck on installing the nuget package, because my library is netstandard (2.0). 2.0.1-beta installs. I can't test the functionality quickly, but it'll probably work just fine :)

Thank you!
