### ISSUE TITLE
[UWP] Button displays a box behind the circle on mouse-hover.

### ISSUE THREAD

**Issue by rdaniel0** [wilsonvargas/ButtonCirclePlugin#21]
On UWP Platform, when the mouse hovers over the button, a highlight box is displayed behind the button. Same issue when button is clicked.

See attached screenshots for clarification.

Normal
![screen shot 2018-01-11 at 11 39 20](https://user-images.githubusercontent.com/18712717/34804389-24dbe11a-f6c4-11e7-8f20-91e93e453bf2.png)
OnHover
![screen shot 2018-01-11 at 11 41 27](https://user-images.githubusercontent.com/18712717/34804461-6e7a40d2-f6c4-11e7-8e9d-575e5ec5197b.png)

**Comment by Croseven** [comment]
I am getting the same on Android, but it only happens if I add an Image to the Image property. Icon seems to crash

**Comment by mzhukovs** [comment]
Please see my PR for this: wilsonvargas/ButtonCirclePlugin#42
