### ISSUE TITLE
[UWP] Default test project NullReferenceException

### ISSUE THREAD

**Issue by rdaniel0** [wilsonvargas/ButtonCirclePlugin#22]
There is a NRE in ButtonCircle.FormsPlugin.UWP.dll on UWP platform.

To reproduce
1. Run test solution in this project on a UWP device
2. Navigate to second page through any button
3. Navigate back to main page.
Observe nullreferenceexception.
`Exception thrown: 'System.NullReferenceException' in ButtonCircle.FormsPlugin.UWP.dll`

**Comment by wilsonvargas** [comment]
Pls check: [fixed a NRE that occured when disposing objects in UWP ](https://github.com/wilsonvargas/ButtonCirclePlugin/commit/b251f89edb1693a8b704a441e4b6ecb57dd3ce51) commit
