### ISSUE TITLE
Icon NullReferenceException

### ISSUE THREAD

**Issue by Croseven** [wilsonvargas/ButtonCirclePlugin#24]
I have the following in XAML 

`<local:CircleButton WidthRequest="50"  HeightRequest="50" x:Name="btnRegisterHorse" BorderColor="#1976D2" BackgroundColor="#1976D2" BorderRadius="20"></local:CircleButton>`
                            
and the following in CS
`btnRegisterHorse.Icon = "register_foul.png";` 

Then it causes my app to crash with the following StackTrace [StackTrace.txt](https://github.com/wilsonvargas/ButtonCirclePlugin/files/1673270/StackTrace.txt)

**Comment by wilsonvargas** [comment]
This is not the correct way to show an image. If you want to show an image you must use the `Image` property like this:

`btnRegisterHorse.Image = "register_foul.png";`
