### ISSUE TITLE
[Android] Image Bitmap must not be updated from background thread

### ISSUE THREAD

**Issue by johnfredrick** [wilsonvargas/ButtonCirclePlugin#27]
My application  crashes in android when i try to access the page which has the circle button and it returns this message:
 Image Bitmap must not be updated from background thread

**Comment by wilsonvargas** [comment]
can you show me your code?

**Comment by wilsonvargas** [comment]
closing the issue as no further response from user.  Feel free to re-open if you run into issues around this again or there are further comments.
