### ISSUE TITLE
There is background issue

### ISSUE THREAD

**Issue by JaeWLee** [wilsonvargas/ButtonCirclePlugin#28]
![default](https://user-images.githubusercontent.com/35772429/36379526-4ede69e8-15c2-11e8-9818-30df733056e1.png)

like this

**Comment by rk2022** [comment]
I'm having the same issue in Android only. ios is fine
![untitled](https://user-images.githubusercontent.com/30193832/36664737-dae1f5da-1afa-11e8-898b-97a699dd90a6.jpg)

**Comment by wilsonvargas** [comment]
It's an image? Maybe you should add a larger image than current...

**Comment by rk2022** [comment]
No it is not an image, I mean the arrow is an image, but for the background I just gave it a BackgroundColor of Hex #19B5B2

**Comment by mariomoramontero** [comment]
Hi, 
First of all congrats for your package, it's incredible useful and very flexible.
but I'm experiencing this issue too on android side with both material and awesome fonts, 

I've noticed this issue has something to be with the Xamarin.Forms version  2.5.0.280555 or the ButtonCircle 2.0.2

After lots of tests, downgrading to forms 2.5.0.122203 and buttonCircle 2.0.1.48-beta removes the black border

**Comment by rk2022** [comment]
Yes, it's true, downgrading the forms will solve the issue, but I don't intend to downgrade forms

**Comment by rk2022** [comment]
@wilsonvargas  
Can you please help me? I really need this to work

**Comment by hytea** [comment]
@wilsonvargas I am having the same issue, on Android only. I am trying to create a button (without a border) which I can change the background color and icon to indicate a particular status. However, I am seeing what @JaeWLee  is seeing with a black circle with a colored box inside which changes dimensions depending on how I set the HeightRequest and WidthRequest.

**Comment by wilsonvargas** [comment]
Maybe you might solve this issue updating your Xamarin.Forms version to 2.5.1.444934 check this [project](https://github.com/wilsonvargas/XamarinChatBot/tree/master/src/ChatBot.Clients), I use my plugin and work fine.

**Comment by hytea** [comment]
That did it! Thank you for the response. I was really hoping to be able to use this awesome plugin. It is great to be able to use font awesome, and other font libraries, to keep icons consistent across all apps. Thanks for your work on this. :+1:

**Comment by wilsonvargas** [comment]
@hytea  you are welcome!! I'm very happy when they like my job. I hope my answer will help to @rk2022, @JaeWLee  and @mariomoramontero 

Regards!
