### ISSUE TITLE
Some problems on real devices.

### ISSUE THREAD

**Issue by idogga** [wilsonvargas/ButtonCirclePlugin#3]
Hello, I' ve trying to use Your solution, but it doesn't work on some real device : phone Honor (Android 6.0) and tablet Dexp (Android 5). On other devices it works fine.
It's normal?

**Comment by idogga** [comment]
But if i enable off button, that work.

**Comment by bezzangi** [comment]
in Android, No problem.

in iOS, I can't call ButtonCircleRenderer.Init(); 
Unknown Identifier.

If I don't call it.
Program crash with System.InvalidOperationException.

**Comment by wilsonvargas** [comment]
Try call: ButtonCircle.FormsPlugin.iOS.ButtonCircleRenderer.Init();
Or
Have you tried to add a key to your Info.plist file? If you have not done that add this key to the file like this:


```xml
<key>UIAppFonts</key>
    <array>
      <string>MaterialIcons-Regular.ttf</string>
    </array>
```

**Comment by worawutt** [comment]
Run from your sample project
iOS Simulator iPhone 8 v11.1 : Not show image
Android hardware LG G2 (API 21): Show both rectangle image and circle

![circle_button_issue](https://user-images.githubusercontent.com/15317912/33160029-a50b4c8a-d04b-11e7-8bed-9b1e5992a4c9.jpg)

**Comment by wilsonvargas** [comment]
Pls check new [version ](https://www.nuget.org/packages/Plugins.Forms.ButtonCircle/)
