### ISSUE TITLE
Background when clicked

### ISSUE THREAD

**Issue by TeuryBazzo** [wilsonvargas/ButtonCirclePlugin#34]
My code in xaml
`local:CircleButton AbsoluteLayout.LayoutBounds=".95,.95,.15,.15"
                                    AbsoluteLayout.LayoutFlags="All"
                                    Image="icn_mais_24"
                                    BackgroundColor="#005F9C"
                                    Command="{Binding NovoDocumentoCommand}"
                                    TextColor="White" 
                                    HeightRequest="70"
                                    WidthRequest="70"  >`

this xaml show correct Button :
![whatsapp image 2018-05-21 at 15 07 12](https://user-images.githubusercontent.com/13906326/40322472-e14bee76-5d08-11e8-8151-2b47cfe3e810.jpeg)

but when i click on the Button it shows the borders

![whatsapp image 2018-05-21 at 15 07 12 1](https://user-images.githubusercontent.com/13906326/40322521-0f025e5e-5d09-11e8-988e-2cb627ead90c.jpeg)

I think that occurs on the property backgroundColor, why when i take off this property, this problem don't occurs

any soluction ?

**Comment by wilsonvargas** [comment]
This issue is similiar to #23 it's solved by assigning a style like "**NoShadow**" in your `style.xml` file:

```xml
<style name="NoShadowButton" parent="android:style/Widget.Button">
        <item name="android:stateListAnimator">@null</item>
</style>
```

And then set this style to `android:buttonStyle` in your main style, like this:
```xml
<item name="android:buttonStyle">@style/NoShadowButton</item>
```

For more information see [this sample file](https://github.com/wilsonvargas/ButtonCirclePlugin/blob/master/test/TestAppButtonCircle/TestAppButtonCircle.Android/Resources/values/styles.xml)

**Comment by wilsonvargas** [comment]
I'm closing the issue as no further response from user. Feel free to re-open if you run into issues around this again or there are further comments.
