### ISSUE TITLE
Problem with references 

### ISSUE THREAD

**Issue by Eliezer10** [wilsonvargas/ButtonCirclePlugin#37]
No se encontró el tipo 'local:CircleButton'. Compruebe que no falta una referencia a un ensamblado y que se han compilado todos los ensamblados a los que se hace referencia.

**Comment by wilsonvargas** [comment]
Tienes que agregar en el inicio de tu Page la referencia al control, esto puedes hacerlo de la siguiente manera: 
```xml
xmlns:controls="clr-namespace:ButtonCircle.FormsPlugin.Abstractions;assembly=ButtonCircle.FormsPlugin.Abstractions"
```
