### ISSUE TITLE
For Android  java.lang.nullpointerexception

### ISSUE THREAD

**Issue by popowich** [wilsonvargas/ButtonCirclePlugin#44]
Hello! 
Help me please. I have a problem with the project on Android.
I kind of connected everything correctly, but this error does not go away:

http://joxi.ru/n2Ykk90FoYa5Qr
http://joxi.ru/Q2Kpp9qF4zQdlA

Compilation options: http://joxi.ru/8An66kNsjB4RLA
http://joxi.ru/KAxzzlMhMWD8Jm

**Comment by wilsonvargas** [comment]
Have you tried this on an emulator or real device? I think xamarin previewer doesn't support custom renderers.

**Comment by wilsonvargas** [comment]
I'm closing the issue as no further response from user. Feel free to re-open if you run into issues around this again or there are further comments.
