### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by behroozbc** [wilsonvargas/ButtonCirclePlugin#6]
hi 
your plugin doesn't work in android 6 

![screenshot 3](https://user-images.githubusercontent.com/20381616/31035964-f7970c3c-a576-11e7-8dc4-9eeb3a2652b1.png)
this code is 
                    <local:CircleButton 
        Icon="ic_directions_bike" 
        FontSize="30" TextColor="Black" 
        HeightRequest="70" WidthRequest="70" 
        BorderThickness="5" BorderColor="Black" 
        BackgroundColor="#DCDCDC" Clicked="CircleButton_Clicked">
                    </local:CircleButton>

**Comment by wilsonvargas** [comment]
This issue was solved in #1 pls check it.

**Comment by wilsonvargas** [comment]
Leave a comment
