### ISSUE TITLE
No button pressed effect when using image

### ISSUE THREAD

**Issue by gunnicus** [wilsonvargas/ButtonCirclePlugin#8]
I'm using .png file as button image, but there is no button click effect when the button is clicked. Below is my code, any help would be appreciated.
` <Grid Grid.Row="0" Grid.Column="0" HorizontalOptions="Center" VerticalOptions="Center">
            <Grid.RowDefinitions>
                <RowDefinition Height="70"/>
                <RowDefinition Height="70"/>
                <RowDefinition Height="70"/>
            </Grid.RowDefinitions>
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="70"/>
                <ColumnDefinition Width="70"/>
                <ColumnDefinition Width="70"/>
            </Grid.ColumnDefinitions>
            <controls:CircleButton Image="test1_70x70.png" HorizontalOptions="Center" Grid.Row="0" Grid.ColumnSpan="3" HeightRequest="70" BorderRadius="70" WidthRequest="70" BorderColor="Black" BorderThickness="5" Clicked="CircleButton_Clicked"/>
            <controls:CircleButton Image="test2_70x70.png" FontSize="30" Grid.Row="1" Grid.Column="0" HeightRequest="70" BorderRadius="70" WidthRequest="70" BorderColor="Black" BorderThickness="5" Clicked="CircleButton_Clicked"/>
            <controls:CircleButton Image="test3_70x70.png" FontSize="30" Grid.Row="1" Grid.Column="2" HeightRequest="70" BorderRadius="70" WidthRequest="70" BorderColor="Black" BorderThickness="5" Clicked="CircleButton_Clicked"/>
            <controls:CircleButton Image="test4_70x70.png"  HorizontalOptions="Center" Grid.Row="2" Grid.ColumnSpan="3"  HeightRequest="70" BorderRadius="70" WidthRequest="70" BorderColor="Black" BorderThickness="5" Clicked="CircleButton_Clicked"/>
        </Grid>`

**Comment by gunnicus** [comment]
I found a workaround, in ButtonCircleRenderer.cs OnElementChanged method, add 
`   Android.Widget.Button thisButton = Control as Android.Widget.Button;
            thisButton.Touch += (object sender, Android.Views.View.TouchEventArgs e2) => {
                if (e2.Event.Action == MotionEventActions.Down)
                {
                    Control.SetBackgroundColor(Android.Graphics.Color.Aqua);
                    System.Diagnostics.Debug.WriteLine("TouchDownEvent");
                }
                else if (e2.Event.Action == MotionEventActions.Up)
                {
                    Control.SetBackgroundColor(Android.Graphics.Color.Black);
                    System.Diagnostics.Debug.WriteLine("TouchUpEvent");
                    Control.CallOnClick();
                }
                   
            };`

This will make button looks high lighted when press.

**Comment by wilsonvargas** [comment]
Thanks, I will add this feature in the next version. Can you close this issue?

**Comment by wilsonvargas** [comment]
Check [lastes version ](https://www.nuget.org/packages/Plugins.Forms.ButtonCircle/1.2.47) this issue was added 😄
